### PR TITLE
-.-

### PR DESCRIPTION
**Pull request by ErkamKahriman**

### CODE REVIEW

**Comment by mote166** [comment]
really?

**Comment by mote166** [comment]
its a confirmation that it has no lags , do not make pull requests for something unnecessary.

**Comment by XFIREGANER** [comment]
With crash

**Comment by XFIREGANER** [comment]
This plugin isn't Complete, So You must complete the plugin after that it will be fast. and without lags

**Comment by XFIREGANER** [comment]
@ErkamKahriman
Do you want the crash?

**Comment by GamakCZ** [comment]
Good job! :D

**Comment by ErkamKahriman** [comment]
:D

**Pull request merged**
